### ISSUE TITLE
API Endpoint with PUT 

### ISSUE THREAD

**Issue by Cortey** [kyma-incubator/Kyma-Showcase#19]
**Description**
It is necessary that the saved image data can be expanded by labels and descriptions

**Reasons**
We need to be able to easily edit the image entry by adding labels and descriptions to it

**Acceptance Criteria**
- [ ] Creating an endpoint
- [ ] Adding new received information to the database entry (adds, not overwrites)
- [ ] Updating image status

**Comment by mwisnia97** [comment]
After PUTing image to DB function throw Error unexpected end of JSON.
