### ISSUE TITLE
Accepting URL as an image input

### ISSUE THREAD

**Issue by Cortey** [kyma-incubator/kyma-showcase#22]
**Description**
As a client I'm able to paste a URL from a webpage instead of having to download the file.

**Reasons**
Increasing ease of use and accessibility 

**Acceptance Criteria**
- [x] Image is loaded from URL
- [x] Image gets saved and processed in same fashion as one uploaded from file

**Additional remarks**
- Stretch Goal

**Comment by mwisnia97** [comment]
There is a problem on the frontend site because CORS blocked fetching data from URL. On the front, we can get the URL, make a preview of the photo and send the URL to the backend. The backend has to download the photo itself.

**Comment by mwisnia97** [comment]
Here is the frontend solution, but it's so so so ugly
[https://stackoverflow.com/questions/15760764/how-to-get-base64-encoded-data-from-html-image/15761420#15761420](https://stackoverflow.com/questions/15760764/how-to-get-base64-encoded-data-from-html-image/15761420#15761420)
