### ISSUE TITLE
Fetching image description

### ISSUE THREAD

**Issue by Lyczeq** [kyma-incubator/Kyma-Showcase#61]
**Description**
As a user, I want to be able to see the image description on the details page.

**Reason**
We will be displaying the details of the clicked photo.

**Acceptance criteria:**
- [x] Clicking a tile takes the user to the details page where he is able to see the image's details
- [x] The details are displayed below the photo

**Additional remarks:**
-  The details are requested by the unique id

**Comment by mwisnia97** [comment]
Kyma bot STOP PLS!
